/*
 * This source file was generated by the Gradle 'init' task
 */
package iqw

import iqw.bin.Executor
import java.io.File

class App {
    fun run(){
        val executor = Executor()
        executor.execute("./speedtest.exe", "--format=json-pretty")
    }
}

fun main() {
    App().run()
}
