/*
 * This source file was generated by the Gradle 'init' task
 */
package org.iqw

import org.iqw.testers.ISpeedTester
import org.iqw.testers.OoklaTester

class App {
    fun run(){
        val tester: ISpeedTester = OoklaTester()
        val data = tester.speedTest()
        print(data.downloadSpeed)
        print(data.uploadSpeed)
    }
}

fun main() {
    App().run()
}
