/*
 * This source file was generated by the Gradle 'init' task
 */
package org.iqw

import org.iqw.database.DatabaseCreator
import org.iqw.database.SpeedTableConfig
import org.iqw.testers.ISpeedTester
import org.iqw.testers.OoklaTester

class App {
    fun run(username: String, password: String){
        val tester: ISpeedTester = OoklaTester()
        val data = tester.speedTest()
        print(data.downloadSpeed)
        print(data.uploadSpeed)

        DatabaseCreator.createDatabaseIfNotExists("SpeedDatabase", username, password)
    }
}

fun main() {
    App().run("root", "Consider963!")
}
