/*
 * This source file was generated by the Gradle 'init' task
 */
package iqw

import org.iqw.App
import kotlin.test.Test

class AppTest {
    @Test fun appHasAGreeting() {
        val classUnderTest = App()
        //assertNotNull(classUnderTest.greeting, "app should have a greeting")
    }
}
